---
# tasks file for ansible-mariadb-galera-cluster
- include: set_facts.yml

- name: Ensure NIC specified in 'galera_cluster_bind_interface' exists
  assert:
    that:
      - galera_cluster_bind_interface in ansible_interfaces
    fail_msg: >-
      The NIC name '{{ galera_cluster_bind_interface }}' specified in
      'galera_cluster_bind_interface' does not exist on the target host.
      Available interfaces are: {{ ansible_interfaces | join(',') }}.

- include: unconfigure_cluster.yml
  when: >
    galera_reconfigure_galera is defined and
    galera_reconfigure_galera

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: max-open-files.yml
  when: >
    ansible_service_mgr == "systemd" and
    mariadb_max_open_files != 0

- include: oom-score-adjust.yml
  when: >
    ansible_service_mgr == "systemd" and
    mariadb_oom_score_adjust != 0

- include: setup_cluster.yml

- include: mysql_users.yml
  tags: mysql-users
  when: mariadb_mysql_users is defined

- include: galera_monitoring.yml
  tags:
    - config_galera_monitoring
  when: galera_enable_galera_monitoring_script

- include: configure_root_access.yml

- include: cacti.yml
  when: galera_enable_cacti_monitoring
