---
- name: set_facts | Setting Debian Facts
  set_fact:
    mariadb_login_unix_socket: /var/run/mysqld/mysqld.sock
  when: ansible_os_family == "Debian"

- name: set_facts | Setting RedHat Facts
  set_fact:
    mariadb_login_unix_socket: /var/lib/mysql/mysql.sock
  when: ansible_os_family == "RedHat"
